### ISSUE TITLE
Inputlar value rangida muammo bor

### ISSUE THREAD

**Issue by fakhriyor21** [abdurahmon27/halalhabits#1]
Signup bilan signin inputda muammo bor ekan

**Comment by abdurahmon27** [comment]
to'g'irlab qo'yaman, rahmat

**Comment by abdurahmon27** [comment]
> Signup bilan signin inputda muammo bor ekan

to'g'irlab qo'yaman, rahmat

**Comment by abdurahmon27** [comment]
just fixed
